---
apiVersion: v1
kind: Service
metadata:
  name: nrf-nnrf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: nrf
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    project: free5gc
    nf: nrf
