apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: Interface
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: Capacity
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: DataNetwork
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
