apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: free5gc-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: free5gc-operator-role
subjects:
- kind: ServiceAccount
  name: free5gc-operator
  namespace: free5gc
