apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: free5gc-operator-role
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: free5gc-operator-role
    app.kubernetes.io/component: operator
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator

rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - amfdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - amfdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.nephio.org
  resources:
  - smfdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - smfdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.nephio.org
  resources:
  - upfdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - upfdeployments/status
  verbs:
  - get
  - patch
  - update
