apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  namespace: free5gc
  name: free5gc-operator-leader-election-role-binding
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: free5gc-operator-leader-election-role-binding
    app.kubernetes.io/component: operator
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: free5gc-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: free5gc-operator
