apiVersion: v1
kind: ServiceAccount

metadata:
  namespace: free5gc
  name: free5gc-operator
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: free5gc-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator
