---
apiVersion: v1
kind: Service
metadata:
  name: amf-namf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: amf
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    project: free5gc
    nf: amf
