apiVersion: req.nephio.org/v1alpha1
kind: DataNetwork
metadata:
  name: internet
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  networkInstance:
    name: vpc-internet
  pools:
    - name: pool1
      prefixLength: 24
  