---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: webui
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
      name: http
  selector:
    project: free5gc
    nf: webui
